export const GAMEASSETS_SOURCE_MAP = [
  `${process.env.PUBLIC_URL}/svg/ui/5/media/gem.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/fb messanger.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/heart.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/logout.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/exit fullscreen.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/fullscreen.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/users group.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/sidebar.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/wi fi on.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/wi fi off.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/settings alt.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/add wallet.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/refresh double.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/settings.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/music note.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/close square.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/tips.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/layers.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/volume up.svg`,
  `${process.env.PUBLIC_URL}/svg/ui/5/media/volume down.svg`,
  `${process.env.PUBLIC_URL}/img/cardroom/preview.jpg`,
  `${process.env.PUBLIC_URL}/img/cardroom/bg.jpg`,
  `${process.env.PUBLIC_URL}/img/uikit/livepokerstudio-logo-light-img-2-1-0-@2.png`,
  `${process.env.PUBLIC_URL}/svg/sprites/navigation.svg`,
]

export default GAMEASSETS_SOURCE_MAP