export const DEFAULT_SESSION_PROPERTY_REALM = 'any'
export const DEFAULT_SESSION_PROPERTY_GAME_ID = '0'
export const DEFAULT_SESSION_PROPERTY_LIVE_MODE = true
export const DEFAULT_SESSION_PROPERTY_DEMO_MODE = false
export const DEFAULT_SESSION_PROPERTY_THRESHOLD = '2.0'
